# Automatically generated file. DO NOT MODIFY
#
# This file is generated by device/fairphone/FP5/setup-makefiles.sh

LOCAL_PATH := $(call my-dir)

ifeq ($(TARGET_DEVICE),FP5)

$(call add-radio-file-sha1-checked,radio/bluetooth.img,bac96b3ddeb8485895751d0fe7373f86a5075162)
$(call add-radio-file-sha1-checked,radio/modem.img,bec28755908f881ffa25195c14bcf86426944943)
$(call add-radio-file-sha1-checked,radio/abl.img,7c30a69bd6c821ffc986a017da74ffe9e7b0a041)
$(call add-radio-file-sha1-checked,radio/aop.img,76703396056db81e424ff55b9e087c07ac8d2ba0)
$(call add-radio-file-sha1-checked,radio/cpucp.img,3db00fde45e520397813e1271c729e781e1b3c9e)
$(call add-radio-file-sha1-checked,radio/devcfg.img,67fc053fce61507ab1f534e9b6d966c62551c22a)
$(call add-radio-file-sha1-checked,radio/dsp.img,05f3d5955c71a070000c18a8c45f6202ce0e8125)
$(call add-radio-file-sha1-checked,radio/featenabler.img,9dec2a1ec66dca0a596fa42dc7a61369842c0cb8)
$(call add-radio-file-sha1-checked,radio/hyp.img,110a969429e37d4472060bc710a5dce3382a1308)
$(call add-radio-file-sha1-checked,radio/imagefv.img,e8d8b0eb6a6d609804994dc39bf72f691346d9f8)
$(call add-radio-file-sha1-checked,radio/keymaster.img,32e8b695583e2b016bca5a4d9f6a3b6d8523173f)
$(call add-radio-file-sha1-checked,radio/multiimgoem.img,efa1bb510a85e3b43e40b26f235cfe26dda27455)
$(call add-radio-file-sha1-checked,radio/qupfw.img,7c62779d53a717c11121cc7a5e5e03cb1553a900)
$(call add-radio-file-sha1-checked,radio/shrm.img,21e37755f353bb66ee98061883ca57ce015fecf1)
$(call add-radio-file-sha1-checked,radio/studybk.img,d03430d5adf267e20ce009e527d452d2f4983eb6)
$(call add-radio-file-sha1-checked,radio/tz.img,62b7b5794db2ff09ac7afe2bca7cf02bde4f27ae)
$(call add-radio-file-sha1-checked,radio/uefisecapp.img,df41fdeb01eaa306edd9a3b710afcb590ba44c1e)
$(call add-radio-file-sha1-checked,radio/xbl.img,0cbf05621c424dc3f816b9d26e072661c35f3025)
$(call add-radio-file-sha1-checked,radio/xbl_config.img,e942a965ae64e729ad02ea4110e45dfeb605bcca)

endif
