# Automatically generated file. DO NOT MODIFY
#
# This file is generated by device/fairphone/FP5/setup-makefiles.sh

LOCAL_PATH := $(call my-dir)

ifeq ($(TARGET_DEVICE),FP5)

$(call add-radio-file-sha1-checked,radio/bluetooth.img,a47f26704db7bef62a2ec1487d7839f6df632f38)
$(call add-radio-file-sha1-checked,radio/modem.img,f1db976377f7dea144e5f4178e58d19b0ef198eb)
$(call add-radio-file-sha1-checked,radio/abl.img,9221a5210ef2499d5597531459286d066c676853)
$(call add-radio-file-sha1-checked,radio/aop.img,93ec08f042f05fa4812fd5bce01066cdb58aaba5)
$(call add-radio-file-sha1-checked,radio/cpucp.img,334ec753e449b570245a3431a4deab207dbcca29)
$(call add-radio-file-sha1-checked,radio/devcfg.img,3863fe4e4bfc3c792513abfade2ec6ad06f40782)
$(call add-radio-file-sha1-checked,radio/dsp.img,ef0e367c802882824bfdf40370e266c495158d17)
$(call add-radio-file-sha1-checked,radio/featenabler.img,3fa947aa340618bf724b943b4e0e89789cdac982)
$(call add-radio-file-sha1-checked,radio/hyp.img,0a49f428d03a4edda6bd093da6f410922638e235)
$(call add-radio-file-sha1-checked,radio/imagefv.img,4faf7a822fcbb8f32f65c447e126f867bdf382e5)
$(call add-radio-file-sha1-checked,radio/keymaster.img,92b9e5e31cfbe07764535fec690a986c304eed43)
$(call add-radio-file-sha1-checked,radio/multiimgoem.img,5f525b3f6d546175e4403dc815398079b31a6216)
$(call add-radio-file-sha1-checked,radio/qupfw.img,d11242ca33f70d2d45959a7948488c274e96a7cb)
$(call add-radio-file-sha1-checked,radio/shrm.img,851bba98ba85b805c8672b20d25f7e6d7021b437)
$(call add-radio-file-sha1-checked,radio/studybk.img,1eb54740375e9b08254e9bf0eea703cf80a5aa26)
$(call add-radio-file-sha1-checked,radio/tz.img,c7b5c9cc11c829249736c46263dace97c8efd007)
$(call add-radio-file-sha1-checked,radio/uefisecapp.img,df18182a53f0b55db59931422db89d17df06a4cb)
$(call add-radio-file-sha1-checked,radio/xbl.img,96223f4d2ea6c252c55ae5823671dc5260f8f7fd)
$(call add-radio-file-sha1-checked,radio/xbl_config.img,1d851358fb43d710cdbd106b601a76fb9f9a0649)

endif
