# Automatically generated file. DO NOT MODIFY
#
# This file is generated by device/fairphone/FP5/setup-makefiles.sh

LOCAL_PATH := $(call my-dir)

ifeq ($(TARGET_DEVICE),FP5)

$(call add-radio-file-sha1-checked,radio/bluetooth.img,293b507bd8d411e7749ed6de3fbc7b8119188892)
$(call add-radio-file-sha1-checked,radio/modem.img,3b885d5942a0806afc1a546fc09aa9b4d5b734c2)
$(call add-radio-file-sha1-checked,radio/abl.img,10c5f845e66e142969f5099c55f0c866e4a29607)
$(call add-radio-file-sha1-checked,radio/aop.img,f699679e87ed0c64c4f855aad3d502cf742570f2)
$(call add-radio-file-sha1-checked,radio/cpucp.img,ef26d8ded456ccf987d0844db356b3c2c808d43d)
$(call add-radio-file-sha1-checked,radio/devcfg.img,665bfcbc66069a2c950c47c7d806126c883aedde)
$(call add-radio-file-sha1-checked,radio/dsp.img,ef0e367c802882824bfdf40370e266c495158d17)
$(call add-radio-file-sha1-checked,radio/featenabler.img,e0160165637802f15f80169316f263f93f7b097f)
$(call add-radio-file-sha1-checked,radio/hyp.img,ad9dd88b86da951d2201c2940c47ce8c307d52aa)
$(call add-radio-file-sha1-checked,radio/imagefv.img,5dba619c6355b7c3765fca6e68b356ac597ca86d)
$(call add-radio-file-sha1-checked,radio/keymaster.img,93dcbb3b9dfabb018b90732256ddefdbd4af3400)
$(call add-radio-file-sha1-checked,radio/multiimgoem.img,43eb913a75abf4afbbc1569673a8f6bbd7b8456a)
$(call add-radio-file-sha1-checked,radio/qupfw.img,b8d6e86dd8c01f6b7778b14a1b4aeaf520e550ab)
$(call add-radio-file-sha1-checked,radio/shrm.img,5766dd09082faf5c1af099c35cb8ed8c0d813e0f)
$(call add-radio-file-sha1-checked,radio/studybk.img,247d64303b33110d7fe13f88078df1cf9e5d9f26)
$(call add-radio-file-sha1-checked,radio/tz.img,262bdbb3c80bfb6d78d654fff4fc3b69f8083031)
$(call add-radio-file-sha1-checked,radio/uefisecapp.img,fa370d6d5d4244f76e4b548d4d96ff924e953d1d)
$(call add-radio-file-sha1-checked,radio/xbl.img,203e79067ce1980f8e67552b1a541da77e57b079)
$(call add-radio-file-sha1-checked,radio/xbl_config.img,a3d6298620d0fbd67351fde269ec39c597a4b384)

endif
